name: Fetch M3U8 Link Hourly

on:
  schedule:
    - cron: '0 * * * *'  # runs at minute 0 every hour
  workflow_dispatch:  # allows manual triggering

jobs:
  fetch-stream:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run fetch script
        run: python fetch_m3u8.py
