name: Fetch Google Sheet Data

on:
  schedule:
    - cron: "0 * * * *" # Runs every hour (UTC)
  workflow_dispatch: # Lets you run manually

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install requests

      - name: Run fetch script
        run: python fetch_sheet.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Updated data from Google Sheet" || echo "No changes to commit"
          git push
