name: Fetch Google Sheet Data

on:
  schedule:
    - cron: "0 * * * *"  # runs every hour (UTC)
  workflow_dispatch:     # allows manual trigger

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install requests

      - name: Run fetch script
        run: python fetch_sheet.py

      - name: Commit and push changes
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${PAT_TOKEN}@github.com/${{ github.repository }}
          git add .
          git commit -m "Updated data from Google Sheet" || echo "No changes to commit"
          git push origin HEAD:${GITHUB_REF#refs/heads/}
